// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28/01/2026, 19.55.48
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Rhein Sullivan/Downloads/point-of-sale_nuxtjs/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Rhein Sullivan/Downloads/point-of-sale_nuxtjs/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Rhein Sullivan/Downloads/point-of-sale_nuxtjs/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Rhein Sullivan/Downloads/point-of-sale_nuxtjs/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Rhein Sullivan/Downloads/point-of-sale_nuxtjs/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Rhein Sullivan/Downloads/point-of-sale_nuxtjs/frontend/stores/**/*.{js,ts,mjs}","C:/Users/Rhein Sullivan/Downloads/point-of-sale_nuxtjs/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Rhein Sullivan/Downloads/point-of-sale_nuxtjs/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Rhein Sullivan/Downloads/point-of-sale_nuxtjs/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Rhein Sullivan/Downloads/point-of-sale_nuxtjs/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Rhein Sullivan/Downloads/point-of-sale_nuxtjs/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Rhein Sullivan/Downloads/point-of-sale_nuxtjs/frontend/app.config.{js,ts,mjs}","C:/Users/Rhein Sullivan/Downloads/point-of-sale_nuxtjs/frontend/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;